spring.application.name=object-storage

spring.datasource.url=jdbc:postgresql://localhost:5432/object_storage
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

server.port=8080
